# Generated by Django 4.2.1 on 2023-10-27 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_account_avt_url_account_background_url_and_more'),
        ('Friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_ship', to='User.account')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET_NULL, related_name='user_friend', to='User.account')),
            ],
        ),
        migrations.CreateModel(
            name='Request_FriendShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REFUSE', 'REFUSE')], default='PENDING')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updateAt', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='User.account')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='User.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requester',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
