# Generated by Django 4.2.1 on 2023-10-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0002_friendship_request_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REFUSE', 'REFUSE')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request_friendship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REFUSE', 'REFUSE')], default='PENDING', max_length=30),
        ),
    ]
