# Generated by Django 4.2.1 on 2023-10-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0003_friendship_status_alter_request_friendship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_friendship',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request_friendship',
            name='updateAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
