# Generated by Django 4.2.1 on 2023-10-29 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_account_avt_url_account_background_url_and_more'),
        ('Friends', '0004_alter_request_friendship_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_friend', to='User.account'),
        ),
    ]
