# Generated by Django 4.2.1 on 2023-10-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avt_url',
            field=models.URLField(default='https://i.pinimg.com/736x/c6/e5/65/c6e56503cfdd87da299f72dc416023d4.jpg'),
        ),
        migrations.AddField(
            model_name='account',
            name='background_url',
            field=models.URLField(default='https://i.pinimg.com/736x/c6/e5/65/c6e56503cfdd87da299f72dc416023d4.jpg'),
        ),
        migrations.AddField(
            model_name='account',
            name='classroom',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER'), ('OTHER', 'OTHER')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AccountProfile',
        ),
    ]
